services:
  server:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.server
    ports:
      - "8080:8080"
    volumes:
      - shared_logs:/app/logs  # For writing CSV logs
      - ../:/app               # <--- MAGIC: Maps local code to container (Live Editing)
    networks:
      - ngao_net

  dashboard:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - server
    volumes:
      - shared_logs:/app/logs  # For reading CSV logs
      - ../:/app               # <--- MAGIC: Maps local code to container
    networks:
      - ngao_net

  client_1:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.client
    command: ["--node-id", "1"]
    depends_on:
      - server
    volumes:
      - ../:/app               # <--- MAGIC: Maps local code to container
    networks:
      - ngao_net

  client_2:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.client
    command: ["--node-id", "2"]
    depends_on:
      - server
    volumes:
      - ../:/app               # <--- MAGIC: Maps local code to container
    networks:
      - ngao_net

volumes:
  shared_logs:

networks:
  ngao_net: